name: "Go Security Scan"

on:
  push:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  gosec-scan:
    uses:  tommzn/github-ci/.github/workflows/gosec.yml@v1.0.9
    secrets:
      slack-channel: ${{ secrets.SLACK_CHANNEL }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
    